/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Util.ImprimeZPL;
import controller.ControlaPreco;
import controller.ControlaProduto;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Preco;
import model.Produto;

/**
 *
 * @author ti1
 */
public class Tela1 extends javax.swing.JFrame {

    ControlaProduto controlaProduto = new ControlaProduto();
    ControlaPreco controlaPreco = new ControlaPreco();

    //Decimal
    DecimalFormat cd = new DecimalFormat("0.00");

    public Tela1() {
        initComponents();

        // Metodo Data atual;
        Date dataHoje = new Date();
        field_data.setDate(dataHoje);

        //Metodo Icone
        setIcon();

        //Impediz maximizar
        setResizable(false);

    }
    public String result;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        combobox_loja = new javax.swing.JComboBox<>();
        field_plu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        field_ean = new javax.swing.JTextField();
        field_desc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        field_quant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        field_venda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        field_promocao = new javax.swing.JTextField();
        field_data = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emissor de Etiquetas Gondolas - ZPL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Emissor de Etiquetas"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Selecione a Loja");

        combobox_loja.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combobox_loja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sta.Cruz", "Floriana", "Mancini", "Muzambinho" }));
        combobox_loja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_lojaActionPerformed(evt);
            }
        });

        field_plu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_pluActionPerformed(evt);
            }
        });
        field_plu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_pluKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Digite o PLU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Digite o EAN");

        field_ean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_eanActionPerformed(evt);
            }
        });
        field_ean.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_eanKeyPressed(evt);
            }
        });

        field_desc.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vigencia");

        field_quant.setText("1");
        field_quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_quantActionPerformed(evt);
            }
        });
        field_quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_quantKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quantidade");

        field_venda.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Preço");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Promoção");

        field_promocao.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("São João Supermercados");

        jLabel8.setText("v1.3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(field_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(combobox_loja, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(field_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(field_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(field_promocao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(field_quant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(field_plu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(field_ean, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combobox_loja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_plu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_ean, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(field_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_quant, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(field_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(field_venda, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(field_promocao))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Utilitarios");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Gerar Lista");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Alterados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_lojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_lojaActionPerformed


    }//GEN-LAST:event_combobox_lojaActionPerformed

    private void field_pluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_pluActionPerformed


    }//GEN-LAST:event_field_pluActionPerformed

    private void field_eanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_eanActionPerformed


    }//GEN-LAST:event_field_eanActionPerformed

    private void field_quantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_quantKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (field_quant.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Inserir quantidade de Etiquetas");
            } else {

                int qtdeEtiquetas = Integer.parseInt(field_quant.getText());

                ImprimeZPL imprimeZPL = new ImprimeZPL();

                //Parametros para função de impressão
                String ImpPLU = field_plu.getText();
                String ImpEAN = (field_ean.getText());
                String ImpDESC = field_desc.getText();
                String ImpPRECO = field_venda.getText();

                imprimeZPL.imprimeEtiquetaZebra(ImpPLU, ImpEAN, ImpDESC, ImpPRECO, qtdeEtiquetas);
                {

                }
                field_plu.setText(null);
                field_ean.setText(null);
                field_desc.setText(null);
                field_quant.setText("1");
                field_venda.setText(null);
                field_promocao.setText(null);
                field_plu.requestFocus();
            }
        }
    }//GEN-LAST:event_field_quantKeyPressed

    private void field_pluKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_pluKeyPressed

        String lj;

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {

                List<Produto> lista = controlaProduto.PLU(field_plu.getText());

                for (Produto produto : lista) {

                    field_desc.setText(String.valueOf(produto.getDescri()));
                    field_ean.setText(String.valueOf(produto.getEan()));
                    field_quant.requestFocus();
                }

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, "Produto não encontrado!", "ATENÇÃO", 2);
            }

            try {

                if (combobox_loja.getSelectedItem().equals("Sta.Cruz")) {
                    result = "27";

                } else if (combobox_loja.getSelectedItem().equals("Floriana")) {
                    result = "35";

                } else if (combobox_loja.getSelectedItem().equals("Mancini")) {
                    result = "43";
                    System.out.println(result);
                } else if (combobox_loja.getSelectedItem().equals("Muzambinho")) {
                    result = "94";

                }

                lj = result;

                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("1yyMMdd");

                String dataFormatada = simpleDateFormat.format(field_data.getDate());
                String data = (dataFormatada);
                String prod = field_plu.getText();
                //String lj = ((combobox_loja.getSelectedItem().toString()));

                // System.out.println(lj);
                List<Preco> lista = controlaPreco.pesquisar(data, lj, prod);

                for (Preco preco : lista) {

                    field_promocao.setText(cd.format(preco.getPoferta()));
                    field_venda.setText(cd.format(preco.getPreco()));

                }

            } catch (Exception exception) {
            }
        }

    }//GEN-LAST:event_field_pluKeyPressed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        dispose();
//        Tela2 x = new Tela2();
//        x.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        dispose();
//        Tela3 x = new Tela3();
//        x.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void field_eanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_eanKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            try {

                List<Produto> lista = controlaProduto.consultaEAN((field_ean.getText()));

                for (Produto produto : lista) {

                    field_desc.setText(String.valueOf(produto.getDescri()));
                    field_plu.setText(String.valueOf(produto.getCodigo()));
                    field_quant.requestFocus();
                }

            } catch (Exception exception) {
                JOptionPane.showMessageDialog(null, "Produto não encontrado!", "ATENÇÃO", 2);
            }

            try {

                if (combobox_loja.getSelectedItem().equals("Sta.Cruz")) {
                    result = "27";

                } else if (combobox_loja.getSelectedItem().equals("Floriana")) {
                    result = "35";

                } else if (combobox_loja.getSelectedItem().equals("Mancini")) {
                    result = "43";

                } else if (combobox_loja.getSelectedItem().equals("Muzambinho")) {
                    result = "94";

                }

                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("1yyMMdd");

                String dataFormatada = simpleDateFormat.format(field_data.getDate());
                String data = (dataFormatada);
                String prod = field_plu.getText();
                //String lj = ((combobox_loja.getSelectedItem().toString()));

                String lj = result;

                List<Preco> lista = controlaPreco.pesquisar(data, lj, prod);

                for (Preco preco : lista) {
                    field_promocao.setText(cd.format(preco.getPoferta()));
                    field_venda.setText(cd.format(preco.getPreco()));
                }

            } catch (Exception exception) {

            }

        }


    }//GEN-LAST:event_field_eanKeyPressed

    private void field_quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_quantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_quantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_loja;
    private com.toedter.calendar.JDateChooser field_data;
    private javax.swing.JTextField field_desc;
    private javax.swing.JTextField field_ean;
    private javax.swing.JTextField field_plu;
    private javax.swing.JTextField field_promocao;
    private javax.swing.JTextField field_quant;
    private javax.swing.JTextField field_venda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    private Tela3 Tela3() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setIcon() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/logo.png")));

    }

}
